services:
  postgres:
    image: postgres:16
    container_name: sakila_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: sakila
    ports:
      - "5432:5432"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge